### ISSUE TITLE
添加@click事件轮动一轮后不生效问题 -- [解决办法]

### ISSUE THREAD

**Issue by edk24** [xiaofulzm/vue3-scroll-seamless#6]
早先给元素添加 @click 事件, 发现滚动一轮后, 会有一大段区域点击是不生效的. 

**问题代码**

```vue
<vue3ScrollSeamless
          class="scroll-wrap tbody"
          :classOptions="classOption"
          :dataList="siteList"
        >
          <div class="table-row" v-for="item in siteList" :key="item.id">
            <div>{{ item.site_name }}</div>
            <div>{{ item.master_name || '-' }}</div>
            <div>{{ item.medicine_ready == 2 ? '已备齐' : '欠缺' }}</div>
            <div>{{ item.ambulance_ready == 2 ? '已到位' : '未到位' }}</div>
            <div @click="handleViewSite(item)" style="pointer-events: auto; cursor: pointer"> <!-- 问题行 -->
              查看
            </div>
          </div>
        </vue3ScrollSeamless>
```

苦于找不到规律, 并且找了很多vue3的替代品, 要么用不成, 要么找不到.  重新打开这个项目的文档碰碰运气,  结果人家已经写清楚了的

[文档链接](https://xiaofulzm.github.io/vue3-scroll-seamless/guide/issuesSolution.html)

但是作者的这个解决方案我看不懂,   于是用了不推荐的方案, dom 监听, 但是不是给每个元素添加点击事件监听, 而是监听全局事件; 其实也能完成这个需求;  并且也靠谱,   

## 解决思路

增加一个 `class="site-view"` 作为元素标识,  增加一个唯一数据给属性 `:id="item.id"`, 方便后续取用

```vue
<vue3ScrollSeamless
          class="scroll-wrap tbody"
          :classOptions="classOption"
          :dataList="siteList"
        >
          <div class="table-row" v-for="item in siteList" :key="item.id">
            <div>{{ item.site_name }}</div>
            <div>{{ item.master_name || '-' }}</div>
            <div>{{ item.medicine_ready == 2 ? '已备齐' : '欠缺' }}</div>
            <div>{{ item.ambulance_ready == 2 ? '已到位' : '未到位' }}</div>
            <div class="site-view" :id="item.id" @click="handleViewSite(item)" style="pointer-events: auto; cursor: pointer"> <!-- 修改了这行 -->
              查看
            </div>
          </div>
        </vue3ScrollSeamless>
```

```js
// Global Click Event Handler
  document.addEventListener('click', function(event: any) { 

    if (event.target.classList.contains('site-view')) {               // 站点查看按钮
      const id = event.target.getAttribute('id');
      const item = siteList.value.find(r=>r.id == id); // 找到当前点击元素这行
      handleViewSite(item); // 具体业务
    } 

  });
```

算是提供一个解决方案吧  :)

**Comment by xiaofulzm** [comment]
看下相关的事件代理文章就会明白了

**Comment by xiaofulzm** [comment]
> 早先给元素添加 @click 事件, 发现滚动一轮后, 会有一大段区域点击是不生效的.
> 
> **问题代码**
> 
> ```
> <vue3ScrollSeamless
>           class="scroll-wrap tbody"
>           :classOptions="classOption"
>           :dataList="siteList"
>         >
>           <div class="table-row" v-for="item in siteList" :key="item.id">
>             <div>{{ item.site_name }}</div>
>             <div>{{ item.master_name || '-' }}</div>
>             <div>{{ item.medicine_ready == 2 ? '已备齐' : '欠缺' }}</div>
>             <div>{{ item.ambulance_ready == 2 ? '已到位' : '未到位' }}</div>
>             <div @click="handleViewSite(item)" style="pointer-events: auto; cursor: pointer"> 
>               查看
>             </div>
>           </div>
>         </vue3ScrollSeamless>
> ```
> 
> 苦于找不到规律, 并且找了很多vue3的替代品, 要么用不成, 要么找不到. 重新打开这个项目的文档碰碰运气, 结果人家已经写清楚了的
> 
> [文档链接](https://xiaofulzm.github.io/vue3-scroll-seamless/guide/issuesSolution.html)
> 
> 但是作者的这个解决方案我看不懂, 于是用了不推荐的方案, dom 监听, 但是不是给每个元素添加点击事件监听, 而是监听全局事件; 其实也能完成这个需求; 并且也靠谱,
> 
> ## 解决思路
> 增加一个 `class="site-view"` 作为元素标识, 增加一个唯一数据给属性 `:id="item.id"`, 方便后续取用
> 
> ```
> <vue3ScrollSeamless
>           class="scroll-wrap tbody"
>           :classOptions="classOption"
>           :dataList="siteList"
>         >
>           <div class="table-row" v-for="item in siteList" :key="item.id">
>             <div>{{ item.site_name }}</div>
>             <div>{{ item.master_name || '-' }}</div>
>             <div>{{ item.medicine_ready == 2 ? '已备齐' : '欠缺' }}</div>
>             <div>{{ item.ambulance_ready == 2 ? '已到位' : '未到位' }}</div>
>             <div class="site-view" :id="item.id" @click="handleViewSite(item)" style="pointer-events: auto; cursor: pointer"> 
>               查看
>             </div>
>           </div>
>         </vue3ScrollSeamless>
> ```
> 
> ```js
> // Global Click Event Handler
>   document.addEventListener('click', function(event: any) { 
> 
>     if (event.target.classList.contains('site-view')) {               // 站点查看按钮
>       const id = event.target.getAttribute('id');
>       const item = siteList.value.find(r=>r.id == id); // 找到当前点击元素这行
>       handleViewSite(item); // 具体业务
>     } 
> 
>   });
> ```
> 
> 算是提供一个解决方案吧 :)

看下相关的事件代理文章就会明白了
